### ISSUE TITLE
日成交量的问题

### ISSUE THREAD

**Issue by FRLXY** [EricZhu-42/SteamTradingSiteTracker-Data#1]
想向您请教学习一下，buff市场的饰品日成交量如何获取，挂刀行情网站的日成交量应该是Steam的吧，，还有就是您要是方便的话，能否给每个饰品做一个成交量曲线，提供一个搜索栏可以对任意商品自由搜索，谢谢大佬

**Comment by EricZhu-42** [comment]
你好，

目前 BUFF 好像没有提供饰品日成交量的接口？我在 BUFF 的主要 API 里都没找到对应的信息；其中，`https://buff.163.com/api/market/goods` 接口返回了一个 `transacted_num` 项，但数值永远为 0，似乎并未投入使用。其他接口的信息可以参考 [该脚本](https://github.com/EricZhu-42/SteamTradingSiteTracker/blob/cd126a86b9de68a9a483acd560e78048ab33dbf1/scripts/url_formats.py) 。

站点显示的日成交量为 Steam Market 日交易量。

搜索功能目前已经在计划中，应该会在 UI 更新后上线（但可能会比较迟，最近不太抽得出时间更新）。

成交量曲线可以考虑，但目前数据库不存饰品的历史信息（站点的历史行情分析功能是离线读取历史数据生成的），也并不持续更新所有饰品的数据，导致很多饰品的数据存在时段性的缺失。考虑到目前我们先前只存了 Steam 平台的交易量，因此可能直接看 Steam Market 的交易量曲线效果会更好？

**Comment by FRLXY** [comment]
十分感谢
